//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JobApplication.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("JobApplication.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accept.
        /// </summary>
        public static string Accept {
            get {
                return ResourceManager.GetString("Accept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actions.
        /// </summary>
        public static string Actions {
            get {
                return ResourceManager.GetString("Actions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can schedule interviews and record hiring decisions directly in the system. .
        /// </summary>
        public static string Application_InterviewAndDecision {
            get {
                return ResourceManager.GetString("Application_InterviewAndDecision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Review applicants’ submissions and update their status according to the process. .
        /// </summary>
        public static string Application_ReviewAndUpdate {
            get {
                return ResourceManager.GetString("Application_ReviewAndUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job Application Management.
        /// </summary>
        public static string ApplicationName {
            get {
                return ResourceManager.GetString("ApplicationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to List.
        /// </summary>
        public static string BackToList {
            get {
                return ResourceManager.GetString("BackToList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close Date.
        /// </summary>
        public static string CloseDate {
            get {
                return ResourceManager.GetString("CloseDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Password.
        /// </summary>
        public static string ConfirmPassword {
            get {
                return ResourceManager.GetString("ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        public static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Date.
        /// </summary>
        public static string CreateDate {
            get {
                return ResourceManager.GetString("CreateDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Job Application.
        /// </summary>
        public static string CreateJobApplication {
            get {
                return ResourceManager.GetString("CreateJobApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create New Job.
        /// </summary>
        public static string CreateNewJob {
            get {
                return ResourceManager.GetString("CreateNewJob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Days Left to Respond .
        /// </summary>
        public static string DaysLeftToRespond {
            get {
                return ResourceManager.GetString("DaysLeftToRespond", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decision.
        /// </summary>
        public static string Decision {
            get {
                return ResourceManager.GetString("Decision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decisions.
        /// </summary>
        public static string Decisions {
            get {
                return ResourceManager.GetString("Decisions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes, delete it!.
        /// </summary>
        public static string Delete_It {
            get {
                return ResourceManager.GetString("Delete_It", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department.
        /// </summary>
        public static string Department {
            get {
                return ResourceManager.GetString("Department", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unauthorized Access.
        /// </summary>
        public static string error_UnauthorizedAccess {
            get {
                return ResourceManager.GetString("error_UnauthorizedAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interview Date and Time.
        /// </summary>
        public static string InterviewDateTime {
            get {
                return ResourceManager.GetString("InterviewDateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can add new job postings and monitor the status of current openings. .
        /// </summary>
        public static string Job_AddAndTrack {
            get {
                return ResourceManager.GetString("Job_AddAndTrack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job applications.
        /// </summary>
        public static string JobApplications {
            get {
                return ResourceManager.GetString("JobApplications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job Description.
        /// </summary>
        public static string JobDescription {
            get {
                return ResourceManager.GetString("JobDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job Posts.
        /// </summary>
        public static string JobPosts {
            get {
                return ResourceManager.GetString("JobPosts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        public static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure ?.
        /// </summary>
        public static string Message_AreYouSure {
            get {
                return ResourceManager.GetString("Message_AreYouSure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this application?.
        /// </summary>
        public static string Message_DeleteApplication {
            get {
                return ResourceManager.GetString("Message_DeleteApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This email is already used by another applicant..
        /// </summary>
        public static string Message_EmailAlreadyInUse {
            get {
                return ResourceManager.GetString("Message_EmailAlreadyInUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone Number.
        /// </summary>
        public static string PhoneNumber {
            get {
                return ResourceManager.GetString("PhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job title.
        /// </summary>
        public static string Position {
            get {
                return ResourceManager.GetString("Position", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reject.
        /// </summary>
        public static string Reject {
            get {
                return ResourceManager.GetString("Reject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember me?.
        /// </summary>
        public static string RememberMe {
            get {
                return ResourceManager.GetString("RememberMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Responded.
        /// </summary>
        public static string Responded {
            get {
                return ResourceManager.GetString("Responded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Response document.
        /// </summary>
        public static string ResponseDocument {
            get {
                return ResourceManager.GetString("ResponseDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resume.
        /// </summary>
        public static string Resume {
            get {
                return ResourceManager.GetString("Resume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Department.
        /// </summary>
        public static string SelectDepartment {
            get {
                return ResourceManager.GetString("SelectDepartment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Job.
        /// </summary>
        public static string SelectJob {
            get {
                return ResourceManager.GetString("SelectJob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Applications.
        /// </summary>
        public static string ShowApplications {
            get {
                return ResourceManager.GetString("ShowApplications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Decisions.
        /// </summary>
        public static string ShowDecisions {
            get {
                return ResourceManager.GetString("ShowDecisions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Jobs.
        /// </summary>
        public static string ShowJobs {
            get {
                return ResourceManager.GetString("ShowJobs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job Application Created Successfully!.
        /// </summary>
        public static string Success_JobAppCreated {
            get {
                return ResourceManager.GetString("Success_JobAppCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job Application Deleted Successfully!.
        /// </summary>
        public static string Success_JobAppDeleted {
            get {
                return ResourceManager.GetString("Success_JobAppDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application State has been Updated Successfully.
        /// </summary>
        public static string Success_JobAppStateUpdated {
            get {
                return ResourceManager.GetString("Success_JobAppStateUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job Application Updated Successfully!.
        /// </summary>
        public static string Success_JobAppUpdated {
            get {
                return ResourceManager.GetString("Success_JobAppUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job Created Successfully.
        /// </summary>
        public static string Success_JobCreated {
            get {
                return ResourceManager.GetString("Success_JobCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job Deleted Successfully.
        /// </summary>
        public static string Success_JobDeleted {
            get {
                return ResourceManager.GetString("Success_JobDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job Updated Successfully.
        /// </summary>
        public static string Success_JobUpdated {
            get {
                return ResourceManager.GetString("Success_JobUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to the Internal Recruitment Management System, designed to streamline the hiring process within the company and document every stage — from posting a job to making a final decision..
        /// </summary>
        public static string System_WelcomeMessage {
            get {
                return ResourceManager.GetString("System_WelcomeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        public static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Application.
        /// </summary>
        public static string UpdateApplication {
            get {
                return ResourceManager.GetString("UpdateApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Job Post.
        /// </summary>
        public static string UpdateJobPost {
            get {
                return ResourceManager.GetString("UpdateJobPost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You cannot delete this job post because it has active applications..
        /// </summary>
        public static string Warning_DeleteActive {
            get {
                return ResourceManager.GetString("Warning_DeleteActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You cannot delete this job application because a decision has already been made regarding it.
        /// </summary>
        public static string Warning_DeleteActiveDecision {
            get {
                return ResourceManager.GetString("Warning_DeleteActiveDecision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You cannot update this job post because it has active applications..
        /// </summary>
        public static string Warning_UpdateActive {
            get {
                return ResourceManager.GetString("Warning_UpdateActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You cannot Update this job application because a decision has already been made regarding it.
        /// </summary>
        public static string Warning_UpdateActiveDecision {
            get {
                return ResourceManager.GetString("Warning_UpdateActiveDecision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome.
        /// </summary>
        public static string Welcome {
            get {
                return ResourceManager.GetString("Welcome", resourceCulture);
            }
        }
    }
}
